basePath: /api/v1
definitions:
  dto.MeResponse:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      phone:
        type: string
      role:
        $ref: '#/definitions/types.UserRole'
      status:
        $ref: '#/definitions/types.Status'
      updated_at:
        type: string
      updated_by:
        type: string
    type: object
  dto.SignupRequest:
    properties:
      access_token:
        description: access token
        type: string
      email:
        description: basic info
        type: string
      name:
        type: string
      phone:
        type: string
    required:
    - access_token
    - email
    - name
    type: object
  dto.SignupResponse:
    properties:
      access_token:
        type: string
      id:
        type: string
    type: object
  dto.UpdateUserRequest:
    properties:
      name:
        type: string
      phone:
        type: string
    type: object
  ierr.ErrorDetail:
    properties:
      details:
        additionalProperties: {}
        type: object
      internal_error:
        type: string
      message:
        type: string
    type: object
  ierr.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/ierr.ErrorDetail'
      success:
        type: boolean
    type: object
  types.Status:
    enum:
    - published
    - deleted
    - archived
    - inactive
    - pending
    type: string
    x-enum-varnames:
    - StatusPublished
    - StatusDeleted
    - StatusArchived
    - StatusInactive
    - StatusPending
  types.UserRole:
    enum:
    - USER
    - ADMIN
    type: string
    x-enum-varnames:
    - UserRoleUser
    - UserRoleAdmin
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
  description: API for CodeGeeky
  termsOfService: http://example.com/terms/
  title: CodeGeeky API
  version: "1.0"
paths:
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Signup
      parameters:
      - description: Signup request
        in: body
        name: signupRequest
        required: true
        schema:
          $ref: '#/definitions/dto.SignupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.SignupResponse'
      summary: Signup
      tags:
      - Auth
  /user:
    put:
      consumes:
      - application/json
      description: Update the current user's information
      parameters:
      - description: Update user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ierr.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ierr.ErrorResponse'
      summary: Update current user
      tags:
      - User
  /user/me:
    get:
      consumes:
      - application/json
      description: Get the current user's information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MeResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/ierr.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ierr.ErrorResponse'
      summary: Get current user
      tags:
      - User
securityDefinitions:
  Authorization:
    description: Enter the token with the `Bearer ` prefix, e.g. `Bearer <token>`.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
